spring.application.name=kiosk
# Server Port
server.port=8080

# Mongo DB Configuration
spring.data.mongodb.uri=mongodb+srv://mauryaankit993535_db_user:Ankit9935@cluster0.8m7b35j.mongodb.net/?appName=Cluster0
spring.data.mongodb.port=27017
spring.data.mongodb.database=kiosk_db

# Logging
logging.level.org.springframework.data.mongodb=INFO