spring.application.name=kiosk
# Server Port
server.port=8080

# Mongo DB Configuration
spring.data.mongodb.host=mongodb+srv://io6ankitmaurya_db_user:SQSW6K8tFMMi5rxN@cluster0.p6avqq7.mongodb.net/?appName=Cluster0
spring.data.mongodb.port=27017
spring.data.mongodb.database=kiosk_db

# Logging
logging.level.org.springframework.data.mongodb=INFO